### ISSUE TITLE
Any hack suggestion to convert equator player into equator

### ISSUE THREAD

**Issue by GokulSoundararajan** [lp1dev/SeaboardHacks#1]
Equator player have lot of limitations & challenges but in equator player we were untied at few cases, I appreciate if anyone could suggest a hack to convert equator player to equator full

https://support.roli.com/support/solutions/articles/36000039076-equator-player-and-equator-compared

**Comment by lp1dev** [comment]
Yes, there actually is a "hack" for this, it's well known and works for other proprietary software you might want to upgrade!
 
Actually buy the thing https://roli.com/products/software/equator-synth.
